- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - php-gd
      - php-xml
      - php-mbstring
      - php-json
      - php-redis
      - unzip
      - curl
      - redis-cli
    state: present

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: Extract WordPress
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/html"
    remote_src: yes

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: Copy Apache configuration for WordPress
  template:
    src: wordpress.config.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Set permissions for WordPress
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    recurse: yes

- name: Enable Apache rewrite module
  command: a2enmod rewrite
  notify: Restart apache2

- name: Reload apache2
  service:
    name: apache2
    state: reloaded

- name: Restart apache2
  service:
    name: apache2
    state: restarted