- name: Install dependencies
  yum:
    name:
      - httpd
      - php
      - php-mysqlnd
      - php-gd
      - php-xml
      - php-mbstring
      - php-json
      - php-redis
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"

- name: Extract WordPress
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/html"
    remote_src: yes

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: Set permissions
  file:
    path: /var/www/html/wordpress
    owner: apache
    group: apache
    recurse: yes